name: Deploy the build to the apprepo (PROD)
on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
  PROD_VERSION_NAME: "latest"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build-image
        run: |
          docker-compose -f docker-compose.yaml build --no-cache --progress=plain
          docker-compose -f docker-compose.yaml run "appimage" make all

      - name: deploy
        run: |

          docker-compose -f docker-compose.yaml run "appimage" /bin/sh -c \
              '/root/bin/Apprepo.AppImage upload /root/`ls /root/ | grep AppImage | head -n 1` --version-description=`date +"%d-%m-%Y"` --version-name="${PROD_VERSION_NAME}" --version-token=${PROD_TOKEN}'
