name: Deploy the build to the apprepo (PROD)
on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  AUTHENTICATION: "${{ secrets.PROD_AUTHENTICATION }}"
  TOKEN: "${{ secrets.PROD_TOKEN }}"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: preparation
        run: |

          mkdir --parents app/.config/
          echo "[user]"                    >  ./app/.config/apprepo/default.conf
          echo "token = ${AUTHENTICATION}" >> ./app/.config/apprepo/default.conf


      - name: build
        run: |

          docker-compose -f docker-compose.yaml build --no-cache --progress=plain
          docker-compose -f docker-compose.yaml run appimage make all

      - name: deploy
        run: |

          docker-compose -f docker-compose.yaml run appimage /bin/sh -c \
              '/root/bin/Apprepo.AppImage upload /root/`ls /root/ | grep AppImage | head -n 1` \
                --version-description=`date +"%d-%m-%Y"` \
                --version-name="latest" \
                --version-token=${TOKEN}'
